overrides:
  postcss: '8.5.15'

allowBuilds:
  sharp: false
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@css-inline/*'
  - '@yedoma-labs/*'
  - '@yedoma-labs/tierde-mail@0.7.0'
  - '@types/node@26.0.0'
